services:
    _defaults:
        autowire: true
        autoconfigure: true

    ErrorWatch\Symfony\EventSubscriber\ConsoleSubscriber:
        arguments:
            $errorSender: '@ErrorWatch\Symfony\Service\ErrorSenderInterface'
            $breadcrumbService: '@ErrorWatch\Symfony\Service\BreadcrumbService'
            $captureExitCodes: '%error_watch.console.capture_exit_codes%'
        tags:
            - { name: kernel.event_subscriber }
