services:
    _defaults:
        autowire: true
        autoconfigure: true

    ErrorWatch\Symfony\Service\DeprecationHandler:
        arguments:
            $client: '@ErrorWatch\Symfony\Http\MonitoringClientInterface'
            $environment: '%error_watch.environment%'
            $release: '%error_watch.release%'
