services:
    _defaults:
        autowire: true
        autoconfigure: true

    ErrorWatch\Symfony\EventSubscriber\MessengerSubscriber:
        arguments:
            $errorSender: '@ErrorWatch\Symfony\Service\ErrorSenderInterface'
            $captureRetries: '%error_watch.messenger.capture_retries%'
        tags:
            - { name: kernel.event_subscriber }
