services:
    Makfly\ErrorMonitoringBundle\Twig\ReplayExtension:
        arguments:
            $replayManager: '@Makfly\ErrorMonitoringBundle\Service\SessionReplayManager'
        tags:
            - { name: twig.extension }
