services:
    Makfly\ErrorWatch\Twig\ReplayExtension:
        arguments:
            $replayManager: '@Makfly\ErrorWatch\Service\SessionReplayManager'
        tags:
            - { name: twig.extension }
