error_watch:
  enabled: true
  endpoint: 'http://localhost:3333'
  api_key: 'changeme'
  environment: '%env(APP_ENV)%'

  monolog:
    enabled: true
    level: warning

  logs:
    enabled: true
    level: debug
